name: parseserver_openid_flutter
description: A package that adds openid authentification to the ParseServer Flutter package.
version: 0.2.0-nullsafety.0
homepage: https://github.com/fischerscode/ParseServer-OpenID-Flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  parse_server_sdk_flutter: ^3.0.0
  oauth2: ^2.0.0
  url_launcher: ^6.0.3

  shared_preferences: ^2.0.5

  uni_links2: ^0.6.0+2

  rxdart: ">=0.24.1 <1.0.0"

  http: ">=0.12.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
